apiVersion: v1
kind: ConfigMap
metadata:
  name: mosbot-dashboard-config
  namespace: mosbot
data:
  VITE_API_URL: "http://mosbot-api.mosbot.svc.cluster.local:3000/api/v1"
  VITE_APP_NAME: "MosBot"
  VITE_APP_VERSION: "1.0.0"
